# Generated by Django 6.0.5 on 2026-05-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
