# Generated by Django 5.2.1 on 2026-07-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sport", "0004_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="date",
            field=models.DateField(),
        ),
    ]
